### ISSUE TITLE
Allow injecting swarmkey into validator pod before validator creates new one

### ISSUE THREAD

**Issue by Spareo** [caseypugh/helium-validator-k8s#11]
This can be done by using a configmap and mounting it to the pod in the stateful set manifest. This would play very nicely with the helm chart and using a values file for configuration

**Comment by caseypugh** [comment]
We discussed this a bit on discord, but this use case is specifically if you are migrating an existing validator to k8s, right? Which means you'd probably want to get the k8s validator in sync _before_ swapping out the swarm key so you arent running duplicate validators. Going to close this
