### ISSUE TITLE
Startup probe error

### ISSUE THREAD

**Issue by caseypugh** [caseypugh/helium-validator-k8s#27]
shouldn't fully error when trying to find this file.
```
Startup probe failed: cat: can't open '/tmp/miner-started': No such file or directory
```

**Comment by jamiew** [comment]
Why not error? Seeing this just means it's not fully started yet and it'll try again a few seconds later. I set the timer based on the average startup time I observed minus a smidge, so that it would become Ready as quickly as possible

**Comment by caseypugh** [comment]
Doesn't seem like it should be throwing an actual error but rather just return "false" if it's not ready yet.

**Comment by jamiew** [comment]
The >0 exit code is how kubernetes does the "false" afaik. Do you mean just silencing the output?
